### ISSUE TITLE
GPU problem after first execution of logging branch

### ISSUE THREAD

**Issue by IvanLetteri** [AAAI-DISIM-UnivAQ/bd-procedural-env-deep-learning#14]
issue during the execution:

_File "/home/mobilews/AgenteRL/NEW_bd-procedural-env-deep-learning/env/lib/python3.9/site-packages/keras/optimizers/optimizer.py", line 1245, in apply_grad_to_update_var
      return self._update_step_xla(grad, var, id(self._var_key(var)))
Node: 'StatefulPartitionedCall_10'
RET_CHECK failure (tensorflow/compiler/xla/service/gpu/gpu_compiler.cc:618) dnn != nullptr 
         [[{{node StatefulPartitionedCall_10}}]] [Op:__inference_train_function_1776]_

**Comment by giodegas** [comment]
not reproducible with current code, please update.
